name: Build & Push

on:
  push:
    branches:
      - master
    tags:
      - 'v*'   # e.g. v1.0.0, v1.0.1, v2.0.0
  workflow_dispatch:

env:
  BACKEND_IMAGE_NAME: jokes
  FRONTEND_IMAGE_NAME: frontend

jobs:
  push_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect release version
        id: release
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "IS_RELEASE=true" >> $GITHUB_ENV
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "IS_RELEASE=false" >> $GITHUB_ENV
            echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version from git tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build & Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./API-jokes
          file: ./API-jokes/Dockerfile.prod
          push: ${{ env.IS_RELEASE == 'true' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  push_frontend:
    runs-on: ubuntu-latest

    needs: push_backend   # wait for backend to finish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect release version
        id: release
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "IS_RELEASE=true" >> $GITHUB_ENV
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "IS_RELEASE=false" >> $GITHUB_ENV
            echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version from git tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build & Push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./react-client
          file: ./react-client/Dockerfile.prod
          push: ${{ env.IS_RELEASE == 'true' }}
          build-args: |
            VITE_API_BASE_URL=http://jokesLB-1114119934.eu-north-1.elb.amazonaws.com
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  deploy_to_AWS:
    runs-on: ubuntu-latest
    needs:
      - push_backend
      - push_frontend

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

