name: Build & Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: frontend

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code to repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest version
        id: version
        run: |
          set -e
          IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}"
          TAG=$(docker manifest inspect $IMAGE:version-tracker --insecure --verbose 2>/dev/null | jq -r '.Descriptor.annotations."org.opencontainers.image.version"' || echo "v1.0.0")
          NUM=$(echo $TAG | awk -F. '{print $3+1}')
          echo "NEW=v1.0.$NUM" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./API-jokes
          file: ./API-jokes/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.NEW }}
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.NEW }}

      - name: Update tracker tag
        run: |
          docker buildx imagetools create \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:version-tracker \
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.NEW }}
